### ISSUE TITLE
Locked wooden doors make metal doors and unlocked metal doors make wood sounds

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/ts_doors#3]
Many doors have odd open/close sounds:

* ALL locked doors make metal sounds, even if they are out of wood
* ALL unlocked doors make wood sounds, even if they are out of metal

IMO the open/close sounds should follow a different rule:

* Wooden doors (no matter if locked or not): Wooden sounds
* Metal doors: Metal sounds
* Diamond doors: Unsure

**Comment by Thomas--S** [comment]
That's a good point. I will change it as soon as possible (maybe tomorrow).

**Comment by Thomas--S** [comment]
50989e786fedd9c0a418c0914cedde84b4cd2e27
