### ISSUE TITLE
Door crafter's crafting is accellerated when quickly adding material multiple times

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/ts_doors#4]
How to reproduce:

* Select windowed wooden trapdoor (arbitrary decision, the point is that it's cheap)
* Get lots of wood
* Make sure all input and output slots are empty
* Now take a 99 wood stack and insert it into the input
* Quickly take another stack and put it again in the input **while the crafting is still in progess**
* Repeat this as often you like

You will soon notice with each additional stack added the crafting is done faster. By abusing this bug, you can craft 99 doors in only a few seconds.

It does not seem to matter whether you add the stacks with sneak-click or “by hand”. But with sneak-click, the effect becomes obvious very quickly.

PS: I have not tested how the mod behaves with regards to steel (for the lock) but I suspect it is buggy, too.

**Comment by Thomas--S** [comment]
I will look what this problem is. Thanks for your help!

**Comment by Thomas--S** [comment]
33af1b0c8002e65c36933dc4740449294dbea4d4 should fix this. Please test this commit. Thank you very much!

**Comment by Wuzzy2** [comment]
Looks good.
