### ISSUE TITLE
Add doors back to creative inventory

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/ts_doors#5]
Can you please add the doors back to creative inventory? Being required to use the door crafter in creative mode is a bit annoying IMO. There are not too many doors in this mod so I don't think they seriously clutter the creative inventory.

**Comment by Thomas--S** [comment]
If you wish this, I will do this.

**Comment by Thomas--S** [comment]
12f69f9ad4dd0a7a4e90efe33e90a64abd279fa6
