### ISSUE TITLE
Mod does not work in 0.4.14 because of metal sounds

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/ts_doors#6]
This mod has become incompatible with 0.4.14 again because you added metal sounds.
Can you please add a fallback routine which checks if the metal sounds are present before adding them? If they are not present, fall back to stone sounds.

Thanks. :-)

**Comment by Thomas--S** [comment]
Ok. Will do this soon :wink:

**Comment by Thomas--S** [comment]
Could you please check if b62782febd4e1525acce0a8d210270593d405c18 solves this issue?

**Comment by Wuzzy2** [comment]
Yes, it works. Thx.
